const categories = {
  realism: [
    "fully realistic", "mostly realistic", "mixed", "somewhat fantastical", "extremely fantastical"
  ],
  narrator: ["first person", "third person"],
  genderNarrator: ["female", "male", "female", "male", "androgynous", "futa", "MTF", "FTM"],
  orientationNarrator: ["100% heterosexual", "mostly heterosexual", "bisexual", "homosexual", "fluid orientation"],
  clothingNarrator: [
    "naked", "painted body (only)", "body covered in mud/oil", "primal rags", "rope only",
  "home wear", "pajamas or sleepwear", "bathrobe and slippers", "loose tank top and shorts", "oversized sweater", "transparent lounge robe",
  "work uniform", "office attire", "lab coat with nothing underneath", "police/military uniform", "maid outfit", "prison jumpsuit",
  "latex catsuit", "leather harness", "corset and heels", "open-cup lingerie", "gag and cuffs set", "puppy/bunny play gear",
  "anime-style school uniform", "magical girl outfit", "demon queen regalia", "elf huntress armor", "cyberpunk street gear", "alien priestess robes",
  "elegant evening gown", "ball dress with slit", "see-through silk dress", "tuxedo (gender-inverted)", "high heels and pearls only", "corset with opera gloves",
  "gender-bending outfit", "feminine outfit on masculine body", "masculine suit on feminine body", "hybridized gender costume", "crossplay armor",
  "cult robes", "sacred veils and body paint", "ceremonial chains", "priestess attire", "nude with symbolic tattoos"
  ],
  tech: ["historical", "present-day", "historical", "present-day", "historical", "present-day", "steampunk", "solarpunk","future", "magic-based", "hybrid (tech & magic)"],
  characters: [
    "alone", "couple", "alone", "couple","alone", "couple", "couple", "couple","three people","three people","three people", "three people", "four (3 to 1)", "two couples", "five (4 to 1)", "group of 5–10 (many to one)", "group of 10–50 (many to one)", "mass of 50–100 (many to one)", "over 100 (many to one)", "uncountably many (many to one)", "group of 5–10 (orgy)", "group of 10–50 (orgy)", "mass of 50–100 (orgy)", "over 100 (orgy)", "uncountably many (orgy)"
  ],
  clothingOthers: [null,
  ],
  genderDistribution: [
    "100% female", "mostly female", "mixed genders", "mostly male", "100% male", "all futa", "futa presence", "MTF dominant", "FTM dominant"
  ],
  orientationOthers: [
    "100% heterosexual", "mostly heterosexual", "bisexual", "lesbian-focused", "fluid orientation"
  ],
  dynamic: [
    "loving and tender", "affectionate with emotional depth","protective and nurturing", "comforting and reassuring", "spiritually connected", "romantic but restrained","flirty and playful",
  "manipulative but sweet",
  "emotionally intense",
  "co-dependent",
  "obsessive and possessive",
  "secretive and hidden",
  "strict and disciplinary",
  "ritualistic and reverent",
  "devotional and worship-based",
  "commanding and obedient",
  "initiatory and transformative",
  "dominant and corrective",
  "animalistic and primal",
  "sensual but detached",
  "experimental and curious",
  "based on mutual pleasure",
  "transactional or professional",
  "unspoken agreement",
  "cold and punishing",
  "hostile with attraction",
  "aggressive but accepted",
  "resentful and conflicted",
  "complex and mixed",
  "emotionally ambiguous"
  ],
  relationship: [
  "strangers",
  "acquaintances",
  "close friends",
  "best friends",
  "ex-lovers",
  "rivals",
  "classmates",
  "co-workers",
  "teacher and pupil",
  "mentor and apprentice",
  "instructor and initiate",
  "employer and employee",
  "boss and subordinate",
  "client and service provider",
  "noble and servant",
  "performer and audience",
  "healer and patient",
  "adoptive siblings",
  "step-siblings",
  "older cousin and younger cousin",
  "cousins",
  "priestess and disciple",
  "ritual guide and novice",
  "initiator and initiate",
  "dominant and submissive",
  "owner and property",
  "dominant and trial subject",
  "prisoner and jailer",
  "savior and rescued",
  "rescuer and dependent",
  "watcher and performer",
  ],
  age: [
  "all participants are young adults",
  "all participants are mature adults",
  "mixed ages, but similar",
  "noticeable age difference",
  "significant age gap",
  "extreme age difference (e.g. centuries)",
  "age not clearly defined or irrelevant"
  ],
  powerImbalance: [
  "total submission",
  "submissive role",
  "brat",
  "rebellious",
  "role subversion",
  "balanced",
  "dominant role",
  "dominant to submissive",
  "submissive to dominant",
  "equal to submissive",
  "equal to dominant",
  "dominant to equal",
  "submissive to equal",
  "switch",
  "absolute control",
  "manipulation",
  "conditioning into submission",
  "protector",
  ],
  consent: [
  "fully consensual",
  "ongoing enthusiastic consent",
  "ritualized or formal consent",
  "consensual non-consent (CNC)",
  "consensual coercion",
  "reluctant consent",
  "initially consensual",
  "frenzied consent",
  "fading consent",
  "ambiguous",
  "final consent only",
  "dubious consent",
  "assumed or inferred consent",
  "coerced through social pressure",
  "coerced through manipulation",
  "drug use",
  "free-use",
  "blackmail",
  "non-consensual"
  ],
 place: [
  // NATURA SELVAGGIA
  "forest",
  "deep forest",
  "bamboo grove",
  "mushroom forest",
  "dense underbrush",
  "riverbank",
  "swamp edge",
  "hidden lagoon",
  "crystal cave",
  "volcanic cavern",
  "salt cave",
  "limestone grotto",
  "underground spring",
  "natural hot spring",
  "canyon ledge",
  "stone archway",
  "jungle ruin",
  "ancient tree hollow",
  "meadow with tall grass",
  "wild orchard",
  "highland cliff",
  "savannah",
  "cliffside outcrop",
  "ravine crossing",
  "stone circle",
  "desert rock formation",
  "cave pool",
  "crater basin",
  "floating island",
  "natural amphitheater",
  "rock bridge",
  "animal burrow tunnel",

  // SPAZI DOMESTICI
  "luxury bedroom",
  "guest bedroom",
  "maid's quarters",
  "shared dormitory",
  "walk-in closet",
  "laundry room",
  "private bathroom",
  "bathtub with cushions",
  "kitchen counter",
  "under kitchen table",
  "pantry room",
  "basement storeroom",
  "attic full of boxes",
  "domestic library",
  "sofa corner",
  "carpeted stairwell",
  "balcony with curtain",
  "garage workshop",
  "house under renovation",
  "private cinema room",
  "padded meditation room",
  "childhood bedroom",
  "mirror vanity station",

  // SPAZI PUBBLICI
  "school classroom",
  "university amphitheater",
  "lab preparation room",
  "faculty lounge",
  "student dorm room",
  "changing room",
  "abandoned locker room",
  "gymnasium equipment area",
  "spa treatment booth",
  "massage table area",
  "public restroom stall",
  "elevator cabin",
  "escalator corridor",
  "library reading booth",
  "public computer station",
  "recording studio",
  "broadcast control room",
  "tattoo parlor booth",
  "salon chair station",
  "nightclub VIP booth",
  "karaoke room",
  "private bar booth",
  "restaurant kitchen",
  "storage freezer",
  "photobooth in mall",
  "supply closet",
  "cinema back row",
  "theater dressing room",

  // TRASPORTI E VEICOLI
  "train compartment",
  "cargo train car",
  "empty subway car",
  "tram platform",
  "airplane lavatory",
  "private jet lounge",
  "airship gondola",
  "ship captain’s cabin",
  "boat cabin bunk",
  "yacht lounge",
  "motorhome interior",
  "convertible car",
  "autonomous vehicle",
  "ride-share car",
  "space shuttle cockpit",
  "hangar floor",
  "drone bay",
  "freight elevator",

  // LUOGHI RITUALI E FANTASY
  "ritual temple",
  "forgotten altar",
  "ancient shrine",
  "priestess sanctum",
  "stone sanctuary",
  "holy bathhouse",
  "catacomb chapel",
  "oracle chamber",
  "prophecy room",
  "crystal circle",
  "glowing runestone hall",
  "magical library",
  "tower observatory",
  "goddess throne room",
  "underground vault",
  "sealed chamber",
  "gilded cage",
  "suspended rope ring",
  "training pit",
  "silken canopy room",
  "royal garden wall",
  "matron's study",
  "initiation chamber",

  // AMBIENTI TECNOLOGICI / DISTOPICI
  "VR simulation room",
  "sensory override room",
  "neon corridor",
  "latex conversion cell",
  "obedience chamber",
  "containment unit",
  "android repair bench",
  "chamber of restraints",
  "automated med bay",
  "observation pod",
  "mental reconditioning room",
  "interrogation seat",
  "AI terminal interface",
  "data chamber",
  "surveillance hub",
  "scanner dock",
  "discipline booth",
  "reprogramming suite",
  "memory editing bay",

  // SURREALI / ONIRICI / SIMBOLICI
  "dreamworld",
  "mirror corridor",
  "infinite staircase",
  "endless hallway",
  "black void platform",
  "giant library with no exit",
  "statue gallery",
  "hanging garden chamber",
  "clockwork passage",
  "theater stage with red curtain",
  "glass labyrinth",
  "fabric maze",
  "crystal bed pedestal",
  "levitating cube chamber",
  "looping room",
  "echo chamber",
  "floating throne",
  "suspended platform",
  "rotating room",
  "mechanical cathedral",
  "living painting room",
  "fractal vault"
  ],
  seasonClimate: [
    // Stagioni classiche
  "spring",
  "early spring",
  "late spring",
  "summer",
  "early summer",
  "late summer",
  "autumn",
  "early autumn",
  "late autumn",
  "winter",
  "early winter",
  "deep winter",
  // Climi naturali
  "tropical",
  "humid jungle",
  "desertic",
  "polar",
  "subarctic",
  "mediterranean",
  "alpine highland",
  "temperate coastal",
  "foggy valley",
  "savannah dry season",
  "monsoon forest",
  "wetland basin",
  // Condizioni atmosferiche
  "rainy season",
  "light drizzle",
  "constant mist",
  "dense fog",
  "stormy weather",
  "thunderstorm sky",
  "blizzard winds",
  "snowfall night",
  "dust storm",
  "hurricane approach",
  "volcanic ash in air",
  "moonlit night",
  "cloudless noon",
  "eclipse dusk",
  // Ambienti artificiali e alterati
  "controlled climate (indoors)",
  "oxygen-regulated chamber",
  "glass dome garden",
  "bio-engineered ecosystem",
  "synthetic rainfall",
  "perfect equilibrium room",
  // Atmosfere oniriche o metafisiche
  "dreamlike atmosphere",
  "time-frozen air",
  "unreal brightness",
  "shadow realm ambiance",
  "eternal sunset",
  "false sky projection",
  "astral shimmer",
  "neon mist twilight"
],
  weather: [
  "clear skies", "sunny with light breeze", "overcast", "rain", "thunderstorm",
  "windy", "dense fog", "snowfall", "blizzard", "humid and tropical", "dry heat",
  "heavy rain with thunder", "light drizzle", "cold and crisp", "hot and still",
  "acid rain", "artificial rain", "purple lightning storm", "dreamlike weather"
],
  time: [ // Ciclo naturale del giorno
  "pre-dawn",
  "dawn",
  "early morning",
  "morning",
  "late morning",
  "midday",
  "early afternoon",
  "afternoon",
  "late afternoon",
  "sunset",
  "twilight",
  "dusk",
  "early evening",
  "evening",
  "late evening",
  "night",
  "deep night",
  "midnight",

  // Tempi simbolici / narrativi
  "first light",
  "last light",
  "golden hour",
  "blue hour",
  "time out of time",
  "frozen moment",
  "looped hour",
  "eternal dusk",
  "stolen midnight",
  "dream interval"
  ],
  exposure: [
     // Isolamento totale
  "complete isolation",
  "deep seclusion",
  "hidden in nature",
  "private room with locked door",
  "sealed chamber",
  "soundproof environment",

  // Intimità protetta
  "dim-lit private space",
  "behind curtains",
  "inside a tent or canopy",
  "under blankets",
  "isolated indoor corner",
  "shared private space (with mutual trust)",

  // Semi-rischio / contesto ambiguo
  "semi-private",
  "soft partitioned space",
  "thin walls",
  "open window",
  "echoes might travel",
  "neighbors nearby",
  "someone in the next room",
  "visible from a distance if noticed",
  "possible mirror reflection",
  "chance of being seen",
  "risk of overhearing",
  "unguarded doorway",
  "partially open public space",

  // Esposizione moderata
  "watched by a silent observer",
  "recorded without permission",
  "audience present",
  "intimate group of trusted onlookers",
  "training display",
  "consensual observation by mentor or superior",
  "accidental walk-in witnessed",
  "shared experience in a ritual setting",

  // Spettacolarizzazione
  "public spectacle",
  "ceremonial presentation",
  "center stage performance",
  "intended display for onlookers",
  "willing audience in themed venue",
  "showroom exhibition",
  "auction scenario",
  "parade or procession scene",

  // Tecnologie e trasmissioni
  "live streamed",
  "surveillance camera present",
  "recorded for archive",
  "delayed release to selected viewers",
  "broadcast on closed channel",
  "projected holographically",
  "interactive stream with viewers",
  "looped playback for review",
  "VR audience presence",
  "forced stream (against participant’s will)",

  // Sovrapposizione tra intimo e pubblico
  "private moment unexpectedly broadcast",
  "stage illusion of privacy",
  "secret live feed",
  "believed alone but monitored",
  "falsely secured environment",
  "exhibition framed as private intimacy"
  ],
  duration: [
    // Durate brevi
  "a few seconds",
  "half a minute",
  "a few minutes",
  "fifteen minutes",
  "half an hour",
  "an hour",
  "a long hour",

  // Sessioni più estese
  "two to three hours",
  "an afternoon",
  "an entire evening",
  "a full night",
  "overnight stay",
  "from dusk till dawn",

  // Archi di più giorni
  "a full day and night",
  "a weekend",
  "three to five days",
  "a week",
  "ten days",
  "several weeks",

  // Lunghi periodi
  "a full month",
  "a season",
  "several months",
  "a year",
  "many years",
  "a decade",
  "a lifetime",

  // Durate narrative o simboliche
  "until exhaustion",
  "until satisfaction",
  "until permission is given",
  "until further notice",
  "outside of time",
  "in a dream that lasts forever",
  "until role is complete",
  "recurring endlessly",
  "time suspended"
  ],
  narrativeContext: [
  // Conflitti e zone di guerra
  "war zone",
  "active battlefield",
  "occupied territory",
  "rebel hideout",
  "post-battle ruins",
  "military encampment",
  "guerrilla camp",
  
  // Criminalità e società oscura
  "criminal underworld",
  "gang hideout",
  "black market den",
  "illegal fighting ring",
  "smuggler’s dock",
  "underground fight club",
  "corrupt police precinct",

  // Luoghi legali e formali
  "courtroom or judiciary",
  "police interrogation room",
  "detention center",
  "lawyer’s office",
  "government building",
  "city hall",

  // Contesti familiari e domestici
  "family home",
  "multi-generational household",
  "suburban neighborhood",
  "small village house",
  "shared apartment",
  "secret room in the house",

  // Locali per vacanze e relax
  "vacation resort",
  "luxury island retreat",
  "remote mountain cabin",
  "tropical beach hut",
  "ski lodge",
  "hidden hot springs",

  // Eventi sociali e festivi
  "public celebration or party",
  "masked ball",
  "street festival",
  "royal banquet",
  "underground rave",
  "carnival parade",

  // Comunità alternative e lifestyle
  "sex-positive commune",
  "cooperative living space",
  "intentional community",
  "hippie commune",
  "artist collective",

  // Professioni e ambienti di lavoro sessuali
  "professional escorting/prostitution",
  "high-end escort agency",
  "massage parlor",
  "gentlemen’s club",
  "strip club",
  "private client’s residence",

  // Ambienti BDSM e fetish
  "BDSM dungeon",
  "private dungeon",
  "underground club",
  "fetish party",
  "bondage studio",

  // Ambienti religiosi e spirituali
  "religious cult",
  "mystical sect",
  "ancient temple",
  "monastery",
  "ritual site",
  "sacred grove",

  // Club e società esclusive
  "elite society club",
  "secretive gentlemen’s club",
  "private members’ lounge",
  "aristocratic salon",

  // Istruzione e formazione
  "school/academy",
  "boarding school",
  "military academy",
  "magical academy",
  "training facility",

  // Ambienti cyberpunk e futuristici
  "cyberpunk district",
  "neon-lit urban sprawl",
  "corporate tower",
  "virtual reality hub",
  "digital metaverse",
  "underground hacker den",

  // Ambienti alieni e fantascientifici
  "alien planet",
  "extraterrestrial colony",
  "intergalactic space station",
  "space ship",
  "terraforming facility",

  // Post-apocalittici e distopici
  "post-apocalyptic bunker",
  "underground fallout shelter",
  "ruined cityscape",
  "wasteland camp",
  "resistance hideout",

  // Strutture mediche e scientifiche
  "medical facility",
  "research hospital",
  "laboratory",
  "cloning center",
  "psychiatric institution",

  // Carceri e ambienti di detenzione
  "prison",
  "maximum security penitentiary",
  "detention camp",
  "rehabilitation center",

  // Militari e sicurezza
  "military base",
  "covert operations center",
  "training ground",
  "security checkpoint",

  // Magia, occulto e fantastico
  "magical academy",
  "arcane university",
  "enchanted forest",
  "wizard’s tower",
  "hidden portal",

  // Società segrete e cospirazioni
  "secret society",
  "hidden cabal",
  "underground resistance headquarters",
  "clandestine meeting room",

  // Spa e centri benessere
  "spa retreat",
  "luxury wellness center",
  "hot spring resort",
  "meditation chamber",

  // Luoghi di piacere e intrattenimento
  "temple of pleasure",
  "ancient ritual site",
  "pleasure palace",
  "erotic theater",

  // Luoghi misteriosi e inquietanti
  "haunted location",
  "abandoned asylum",
  "underground tunnels",
  "forgotten crypt",
  "cursed village",

  // Ambientazioni urbane e insolite
  "floating city",
  "subterranean metro",
  "skybridge walkway",
  "rooftop garden",
  "hidden alleyway",

  // Contesti sociali e culturali
  "post-human enclave",
  "android commune",
  "clan stronghold",
  "nomadic tribe camp",
  "urban squat",

  // Fantastico / mitologico
  "fae glen",
  "dragon’s lair",
  "celestial palace",
  "underwater city"
  ],
  goal: [
  // Espressioni emotive e affettive
  "express affection",
  "create emotional bond",
  "celebrate a union",
  "reaffirm love",
  "seek forgiveness",
  "offer reassurance",
  "strengthen trust",
  "share vulnerability",
  "explore intimacy",

  // Procreazione e fertilità
  "impregnation",
  "fertility ritual",
  "secure lineage",
  "ensure bloodline continuation",
  "ritual conception",

  // Gioco, divertimento e piacere
  "play and fun",
  "casual encounter",
  "sexual exploration",
  "satisfy curiosity",
  "experience new sensations",
  "engage in fantasy",
  "escape reality",
  "indulge in hedonism",
  "experiment with roles",

  // Potere e dominio
  "assert dominance",
  "offer submission",
  "punish disobedience",
  "reward obedience",
  "gain prestige",
  "establish hierarchy",
  "test limits",
  "explore control dynamics",
  "affirm authority",
  "challenge power",

  // Sovraffazione e sopraffazione degli altri
  "dominate and overpower",
  "subjugate partner",
  "humiliate and degrade",
  "break resistance",
  "assert total control",
  "enforce absolute obedience",
  "manipulate and control",
  "exploit vulnerabilities",
  "intimidate and coerce",
  "reduce to submission",
  "explore non-consent dynamics",
  "inflict punishment",
  "demand servitude",
  "erode autonomy",
  "impose will",
  "use as a tool or plaything",
  "exert psychological control",
  "explore power imbalance extremes",

  // Guadagni materiali e sociali
  "earn material wealth",
  "gain favors",
  "secure protection",
  "increase social standing",
  "forge alliances",

  // Esperienze mentali e spirituali
  "meditative experience",
  "spiritual awakening",
  "achieve transcendence",
  "channel divine energy",
  "fulfill a ritual",
  "connect with higher power",
  "ritual purification",
  "spiritual cleansing",

  // Umiliazione e degradazione
  "debase oneself",
  "degrade others",
  "humiliate partner",
  "explore taboo",
  "embrace vulnerability",
  "experience catharsis",
  "reclaim shame",
  "process guilt",

  // Sicurezza e protezione
  "neutralise a threat",
  "provide comfort",
  "seek refuge",
  "establish safety",
  "heal emotional wounds",
  "build resilience",

  // Controllo e disciplina
  "train obedience",
  "enforce rules",
  "discipline oneself",
  "maintain order",
  "practice submission",
  "explore punishment",

  // Altri scopi specifici
  "exchange knowledge",
  "create art",
  "strengthen community bonds",
  "celebrate rites of passage",
  "commemorate an event",
  "test loyalty",
  "overcome fears",
  "seek redemption",
  "explore identity",
  "experience transformation",
  "manifest desire",
  "satisfy addiction",
  "enact revenge",
  "express gratitude",
  "share secrets",
  "forge spiritual bonds"
  ]
};
categories.clothingOthers = categories.clothingNarrator;

function getSpeciesByProbability() {
  const roll = Math.random();
  if (roll < 0.7) return "humans only";
  if (roll < 0.9) return "humanoid creatures (e.g., demons, succubi)";
  if (roll < 0.95) return "mix of humanoids and beasts";
  return "beasts only";
}

// 🎯 Nuove categorie con possibilità di ripetizione limitata
const objectPool = [
  "no object involved",

  // Arredi e superfici comuni
  "bed",
  "shower",
  "mirror",
  "couch",
  "floor mats",
  "pillows",
  "table",
  "stool",
  "swing",
  "chains",
  "ropes",
  "cage",
  "bench",
  "bath tub",
  "hammock",
  "curtains",
  "carpet",
  "dresser",
  "bookshelf",
  "armchair",
  "massage table",
  "floor cushions",
  "rocking chair",
  "pouf",
  "ottoman",
  "fireplace hearth",
  "window sill",
  "balcony railing",
  "door frame",
  "stair railing",
  "platform",
  "trapeze bar",
  "gym rings",
  "pole dance pole",
  "loft bed frame",

  // Strumenti e attrezzi BDSM
  "leash",
  "latex gloves",
  "restraints",
  "blindfold",
  "gag",
  "dildo",
  "buttplug",
  "vibrator",
  "pillory",
  "whip",
  "crop",
  "flogger",
  "paddle",
  "clamps",
  "spreaders",
  "collar",
  "rope harness",
  "strap-on",
  "corset",
  "handcuffs",
  "chain leash",
  "electro-stimulation device",
  "nipple rings",
  "cage mask",
  "bondage tape",
  "gag ball",
  "locking chains",
  "iron shackles",
  "spiked collar",
  "bit gag",
  "metal cuffs",
  "mask with muzzle",
  "stockade",
  "rope gag",
  "latex hood",
  "breath control device",
  "wax play candle",
  "fire cupping set",
  "needle play kit",
  "pins",
  "medical clamps",
  "tickler",
  "feather wand",
  "silk ties",
  "latex catsuit",
  "latex stockings",
  "latex hood",
  "corset laces",
  "bondage rope",
  "suspension rig",
  "cattle prod",
  "ball stretcher",
  "vacuum pump",
  "sound chastity device",
  "anal beads",
  "gag harness",
  "spreader bar",
  "clip-on chains",
  "mask with horns",
  "shibari rope set",
  "pinwheel",
  "chain harness",
  "corset busk",
  "gag with microphone",

  // Oggetti di stimolazione sensoriale
  "feather tickler",
  "massage oil",
  "ice cubes",
  "warming balm",
  "silk scarf",
  "fur mittens",
  "sensory brush",
  "sound machine",
  "aromatherapy diffuser",
  "candles",
  "blindfold with bells",
  "ear plugs",
  "massage roller",
  "vibrating cock ring",
  "heated stones",
  "hot wax",
  "chilled metal rod",
  "plush toy",
  "massage candle",
  "body paint",
  "licking mittens",
  "silicone scrubber",
  "body feather",
  "perfume",
  "essential oils",
  "electric pulse wand",
  "soft flogger",
  "warm compress",
  "silk ribbon",
  "scented incense",
  "massage gloves",
  "soft fur brush",
  "chalk powder",
  "massage balls",
  "hot towel",
  "cold gel pack",
  "vibrating nipple clamps",
  "electrodes",
  "hot stone set",
  "satin sheets",
  "scented bath salts",
  "latex paint",
  "sensory deprivation hood",

  // Oggetti tecnologici e moderni
  "VR headset",
  "remote control vibrator",
  "smart restraints",
  "body sensors",
  "temperature control device",
  "microphone",
  "camera for live streaming",
  "speaker system",
  "smart lighting",
  "electric shock collar",
  "wireless earphones",
  "body tracking suit",
  "digital timer",
  "motion sensor",
  "smartwatch",
  "tablet",
  "smartphone",
  "laser pointer",
  "electric massage device",
  "ultrasound stimulator",
  "neural interface headset",
  "haptic feedback gloves",
  "voice modulator",
  "drones",
  "projector",
  "hologram generator",
  "laser grid",
  "electric toothbrush",
  "biofeedback device",
  "electro muscle stimulator",
  "sleep monitoring device",
  "fitness tracker",
  "wireless charging pad",
  "augmented reality glasses",
  "smart lock",
  "security camera",
  "motion activated lights",
  "robotic arm",
  "infrared thermometer",

  // Oggetti insoliti e fantasy
  "magical amulet",
  "enchanted chains",
  "crystal ball",
  "levitating platform",
  "alchemy set",
  "spellbook",
  "enchanted whip",
  "glowing cuffs",
  "phantom restraints",
  "runed collar",
  "magic lantern",
  "ethereal ribbons",
  "shadow cloak",
  "mana-infused chain",
  "arcane crystal",
  "binding scroll",
  "enchanted gag",
  "spirit mask",
  "demonic sigil",
  "ritual dagger",
  "celestial robes",
  "phoenix feather",
  "dragon scale bracers",
  "ghostly shackles",
  "cursed lock",
  "arcane cage",
  "soul gem",
  "time distortion clock",
  "illusion mirror",
  "magical tattoos",
  "portal stone",
  "teleportation ring",
  "elemental orb",
  "arcane wand",
  "spell scroll",
  "enchantment powder",
  "curse amulet",
  "magical chainsaw",
  "levitation boots",
  "mana crystal staff",
  "runed mask",
  "ghost chain whip",
  "mystic incense",
  "witch's broomstick",
  "druidic staff",
  "enchanted dagger",
  "arcane grimoire",
  "spellcasting gloves",
  "magical binding rope",
  "crystal shackles",

  // Oggetti personali o cosplay
  "school uniform",
  "maid outfit",
  "police badge",
  "military boots",
  "business suit",
  "mask",
  "handkerchief",
  "gloves",
  "hat",
  "boots",
  "belt",
  "wristwatch",
  "sunglasses",
  "leather jacket",
  "latex bodysuit",
  "stockings",
  "thigh-high boots",
  "cape",
  "face paint",
  "fake tail",
  "ears headband",
  "maid apron",
  "police baton",
  "military helmet",
  "spyglass",
  "tattoo sleeve",
  "corset belt",
  "lace gloves",
  "capelet",
  "cape hood",
  "faux fur stole",
  "ear cuffs",
  "eye patch",
  "sheriff badge",
  "spy glasses",
  "military epaulets",
  "gloves with claws",
  "chainmail gloves",
  "ninja mask",
  "samurai armor pieces",
  "feathered headdress",
  "pirate hat",
  "corset with garters",
  "latex gloves with claws",
  "combat boots",
  "festival mask",
  "leather harness",
  "nurse uniform",
  "police uniform",
  "chef hat",
  "butler outfit",

  // Oggetti di comfort e cura
  "blanket",
  "soft cushions",
  "water bottle",
  "first aid kit",
  "cooling gel",
  "eye drops",
  "towels",
  "soothing balm",
  "heating pad",
  "herbal tea",
  "massage stones",
  "aroma candles",
  "moisturizer",
  "lip balm",
  "relaxing music player",
  "eye mask",
  "silk pillowcase",
  "humidifier",
  "face mask",
  "bathrobe",
  "fluffy slippers",
  "hot water bottle",
  "cold compress",
  "electric blanket",
  "humidifier",
  "neck pillow",
  "lavender sachet",
  "soothing lotion",
  "sleep mask",
  "ear plugs",
  "relaxation eye gel",
  "body scrub",
  "hairbrush",
  "perfumed body oil",

  // Oggetti per esposizione o spettacolo
  "stage",
  "spotlight",
  "microphone stand",
  "camera",
  "tripod",
  "projector screen",
  "costume accessories",
  "decorative chains",
  "fog machine",
  "disco ball",
  "colored lights",
  "backdrop curtain",
  "camera crane",
  "dancer pole",
  "stage trapdoor",
  "smoke machine",
  "laser lights",
  "pyrotechnics",
  "confetti cannon",
  "stage curtains",
  "DJ booth",
  "soundboard",
  "light rigging",
  "costume wardrobe",
  "portable speakers",

  // Oggetti per ambientazioni particolari
  "airship helm",
  "ancient altar",
  "stone throne",
  "enchanted garden bench",
  "ritual dagger",
  "ceremonial robes",
  "scroll",
  "magic lantern",
  "candelabrum",
  "tapestry",
  "enchanted bookstand",
  "arcane circle",
  "sacred bowl",
  "holy water vessel",
  "scroll holder",
  "ritual incense burner",
  "wooden staff",
  "dragon skull",
  "crystal orb",
  "enchanted mirror",
  "ancient tome",
  "magic potion bottle",
  "sacred relic",
  "ritual mask",
  "enchanted sword",
  "holy symbol",
  "crystal chandelier",
  "totem pole",
  "spirit jar",
  "magic circle mat",
  "ritual chalice",
  "sacred flame torch",
  "magical seal",
  "enchanted armor piece",

  // Oggetti naturali usati come strumenti
  "vines",
  "tree branch",
  "flower petals",
  "leaves",
  "sand",
  "rocks",
  "feathers",
  "shells",
  "pine cones",
  "moss",
  "berries",
  "clay",
  "animal bones",
  "driftwood",
  "thorn branch",
  "flower garland",
  "acorns",
  "dried herbs",
  "crystals",
  "tree bark pieces",
  "seashell necklace",
  "feather headdress",
  "fur pelts",
  "honeycomb",
  "seed pods",
  "mushroom spores",
  "pine needles",

  // Altri oggetti variegati
  "hand fan",
  "parasol",
  "umbrella",
  "picnic basket",
  "musical instrument",
  "drum",
  "flute",
  "harp",
  "violin",
  "lute",
  "tambourine",
  "accordion",
  "kazoo",
  "bagpipes",
  "guitar",
  "piano keyboard",
  "xylophone",
  "bell",
  "gong",
  "chime",
  "wind chime",
  "megaphone",
  "letter opener",
  "writing quill",
  "ink bottle",
  "scroll paper",
  "feather pen",
  "wax seal",
  "map",
  "lantern",
  "torch",
  "candle holder",
  "compass",
  "spyglass",
  "pocket watch",
  "magnifying glass",
  "lockpick set",
  "keyring",
  "jewelry box",
  "ring",
  "necklace",
  "bracelet",
  "earrings",
  "brooch",
  "cufflinks",
  "belt buckle",
  "handbag",
  "wallet",
  "purse",
  "hat pin",
  "button set",
  "hairpin",
  "scarf",
  "shawl",
  "glasses",
  "sunglasses",
  "tie",
  "bowtie",
  "cane",
  "walking stick",
  "pocket mirror",
  "perfume bottle",
  "lipstick",
  "compact powder",
  "nail polish",
  "hairbrush",
  "comb",
  "toothbrush",
  "razor",
  "shaving kit",
  "soap bar",
  "towel",
  "bathrobe",
  "slippers",

  // Oggetti di gioco e divertimento
  "board game",
  "cards",
  "dice",
  "chess set",
  "puzzle",
  "toy car",
  "stuffed animal",
  "jump rope",
  "hula hoop",
  "ball",
  "frisbee",
  "kite",
  "yo-yo",
  "roller skates",
  "skateboard",
  "bicycle",
  "swing set",
  "slide",
  "sandbox",
  "trampoline",
  "water gun",
  "bubble wand",
  "magic kit",
  "costume mask",
  "puppet",
  "marionette",
  "juggling balls",
  "clown nose",
  "face paint kit",
  "toy sword",
  "rubber duck",
  "playdough",
  "crayons",
  "paintbrush",
  "easel",
  "canvas",
  "model airplane",
  "lego bricks",
  "building blocks",

  // Oggetti per animali domestici o bestiali
  "pet collar",
  "leash",
  "pet bed",
  "feeding bowl",
  "chew toy",
  "pet brush",
  "pet carrier",
  "cat tree",
  "dog house",
  "bird cage",
  "aquarium",
  "hamster wheel",
  "animal costume",
  "animal mask",
  "pet harness",
  "pet costume",
  "animal bell",
  "pet tag",
  "animal whistle",
  "animal treats",
  "animal leash holder",
  "pet training clicker",
  "animal play tunnel",
  "animal ball toy",
  "pet water dispenser",
  "animal scratching post",

  // Oggetti per la cura sessuale e igiene
  "lubricant",
  "condoms",
  "sanitary wipes",
  "toilet paper",
  "hand sanitizer",
  "intimate wash",
  "massage oil",
  "intimate wipes",
  "body wash",
  "mouthwash",
  "dental floss",
  "toothpaste",
  "brush",
  "tampons",
  "pads",
  "cotton balls",
  "cotton swabs",
  "hair ties",
  "hair clips",
  "hair spray",
  "perfume",
  "deodorant",
  "aftershave",
  "body powder",
  "breath freshener",
  "facial cleanser",
  "exfoliating scrub",
  "moisturizer",
  "facial toner",
  "sunblock",
  "tanning lotion",
  "body butter",
  "foot cream",
  "hand cream",
  "nail clippers",
  "nail file",
  "cuticle pusher",
  "tweezers",
  "scissors",
  "ear cleaner",
  "eyelash curler",
  "makeup remover",
  "cosmetic brushes",
  "foundation",
  "blush",
  "eyeshadow",
  "mascara",
  "eyeliner",
  "lip gloss",
  "lipstick",

  // Oggetti per il sesso orale
  "oral sex condom",
  "flavored lubricant",
  "oral sex toy",
  "breath freshener strips",
  "mouthwash",
  "toothpick",
  "tongue cleaner",
  "oral hygiene spray",
  "vibrating tongue ring",
  "oral gel",
  "flavored lip balm",
  "oral sex enhancer",
  "oral desensitizing spray",

  // Oggetti per la masturbazione
  "masturbator sleeve",
  "fleshlight",
  "vibrating egg",
  "clitoral stimulator",
  "anal plug",
  "masturbation lotion",
  "masturbation oil",
  "warming gel",
  "cooling gel",
  "massage candle",
  "vibrating ring",
  "stroker",
  "masturbation beads",
  "masturbation powder",

  // Oggetti per il bondage avanzato
  "suspension rig",
  "shibari ropes",
  "chain harness",
  "spreader bar",
  "locking shackles",
  "metal collar",
  "breath control mask",
  "gag with microphone",
  "electrodes set",
  "wax play set",
  "needle play kit",
  "sensory deprivation hood",
  "cage mask",
  "locking corset",
  "ball gag",
  "bit gag",
  "rope gag",
  "chain leash",
  "spiked collar",
  "iron shackles",
  "locking chains",
  "cattle prod",

  // Oggetti di arredamento e atmosfera (luci, tessuti)
  "string lights",
  "LED strip lights",
  "colored bulbs",
  "candles",
  "incense sticks",
  "scented oil diffuser",
  "blackout curtains",
  "silk sheets",
  "velvet curtains",
  "fur rugs",
  "plush pillows",
  "draped fabric",
  "mirrored walls",
  "glitter confetti",
  "sparkling crystals",
  "decorative lanterns",
  "hanging crystals",
  "reflective disco ball",

  // Oggetti di abbigliamento fetish avanzato
  "latex catsuit",
  "PVC dress",
  "bondage harness",
  "leather corset",
  "fishnet stockings",
  "thigh high boots",
  "latex gloves",
  "mask with muzzle",
  "hooded latex suit",
  "spiked heels",
  "collar with leash",
  "wrist cuffs",
  "ankle cuffs",
  "gothic jewelry",
  "metal harness",
  "spiked bracelets",
  "gothic choker",
  "bondage belt",
  "lace garters",
  "latex hood",
  "fetish bodysuit",

  // Oggetti personali extra
  "wallet",
  "phone case",
  "keychain",
  "hand fan",
  "wallet chain",
  "ring",
  "necklace",
  "earrings",
  "bracelet",
  "anklet",
  "watch",
  "hair band",
  "hat",
  "scarf",
  "gloves",
  "sunglasses",

  // Oggetti casuali di uso quotidiano
  "book",
  "notebook",
  "pen",
  "water bottle",
  "coffee mug",
  "backpack",
  "umbrella",
  "wallet",
  "keys",
  "phone",
  "headphones",
  "laptop",
  "charger",
  "glasses",
  "hand sanitizer",
  "lip balm",
  "snacks",
  "wallet",
  "bus ticket",
  "calendar",
  "sticky notes",
  "scissors",
  "tape",
  "glue stick",

  // Oggetti per la cucina
  "knife",
  "fork",
  "spoon",
  "plate",
  "bowl",
  "cup",
  "glass",
  "cutting board",
  "blender",
  "stove",
  "microwave",
  "fridge",
  "teapot",
  "coffee maker",
  "kitchen towel",
  "pot",
  "pan",
  "colander",
  "whisk",
  "measuring cup",
  "salt shaker",
  "pepper grinder",
  "mixing bowl",
  "oven mitts",
  "timer",
  "rolling pin",
  "grater",
  "strainer",
  "can opener",
  "ladle",

  // Oggetti per la pulizia
  "broom",
  "mop",
  "vacuum cleaner",
  "dustpan",
  "cleaning cloth",
  "disinfectant spray",
  "soap",
  "bucket",
  "sponges",
  "brush",
  "gloves",
  "trash bag",
  "duster",
  "floor cleaner",
  "window cleaner",
  "toilet brush",
  "scrubbing pad",
  "cleaning wipes",
  "air freshener",
  "lint roller",
  "squeegee",
  "rubber gloves",

  // Oggetti per il tempo libero
  "book",
  "magazine",
  "tablet",
  "gaming console",
  "board game",
  "cards",
  "puzzle",
  "paint set",
  "music player",
  "headphones",
  "notebook",
  "camera",
  "binoculars",
  "flashlight",
  "tent",
  "sleeping bag",
  "backpack",
  "water bottle",
  "compass",
  "hat",
  "sunglasses",
  "binoculars",
  "hiking boots",

  // Oggetti da collezione
  "stamps",
  "coins",
  "figurines",
  "postcards",
  "vintage books",
  "rare comics",
  "antique jewelry",
  "old maps",
  "action figures",
  "limited edition cards",
  "collectible pins",
  "model cars",
  "signed posters",
  "vintage toys",
  "rare coins",
  "old photographs",
  "memorabilia",
  "antique watches",
  "collector's edition books",
  "rare vinyl records",
];

const kinkPool = [
  // Posizioni sessuali base e varianti
  "oral", "anal", "missionary", "doggy", "cowgirl", "reverse cowgirl", "spooning", "standing", "69", "side-by-side", "scissoring", "wheelbarrow", "pretzel",
  "face-to-face", "cross-legged", "lotus position", "standing rear entry", "lap dance", "face sitting", "bridal carry", "straddle", "standing wheelbarrow", "tabletop",

  // Bondage e restrizione
  "bondage", "shibari", "rope bondage", "handcuffs", "chains", "mummification", "hogtie", "suspension bondage", "spread eagle", "crotch rope", "blindfold", "gagging", "collaring",
  "tape bondage", "duct tape bondage", "bondage tape", "predicament bondage", "metal bondage", "leather restraints", "furniture bondage", "zipties", "arm binder", "hogtie with spreader bar",
  "breast bondage", "chastity belt", "latex bondage", "corset bondage", "sensory restriction",

  // Giochi di ruolo e dinamiche di potere
  "dominazione", "sottomissione", "dominatrice", "submissive", "master/slave", "pet play", "age play", "schoolgirl", "teacher/student", "doctor/patient", "interrogation play",
  "cuckolding", "cuckolding humiliation", "cuckquean play", "hotwife", "obedience training", "obedience reward/punishment", "humiliation erotica",
  "owner/pet", "princess/prince", "slave training", "degradation play", "financial domination (findom)", "servitude",
  "obedience drills", "protocol training", "slave worship", "goddess worship", "pimp/ho roleplay", "kidnap play", "captor/captive", "queen/subject",

  // Giochi sensoriali
  "sensation play", "temperature play", "ice play", "wax play", "fire play", "feather play", "tickling", "massage", "electric play", "vibration play", "nipple clamps", "clit clamps",
  "body worship", "foot play", "hand fetishism", "hair pulling", "ear nibbling", "scratch play", "light scratching", "pinching", "cupping",
  "cold sensation", "heat sensation", "sensory teasing", "sensory overload", "sensory deprivation", "brush play", "silk play", "fur play",

  // Pratiche fetish specifiche
  "latex fetish", "leather fetish", "spandex fetish", "uniform fetish", "stockings", "high heels fetish", "corset fetish", "foot fetish", "armpit fetish", "femdom boots", "pantyhose fetish",
  "latex hood", "rubber suit", "PVC fetish", "bondage hood", "gloves fetish", "mask fetish", "fetish boots", "socks fetish", "gimp suit",
  "clothing destruction fetish", "stiletto fetish", "nylon fetish", "suspenders fetish", "military uniform fetish", "maid fetish", "school uniform fetish",
  "latex gloves", "rubber boots", "ball gag fetish", "scent fetish",

  // Pratiche di stimolazione specifica
  "orgasm denial", "edging", "forced orgasm", "multiple orgasms", "orgasm control", "deepthroat", "face sitting", "pegging", "rimming", "anal fingering", "double penetration",
  "fisting", "gaping", "clit pumping", "urethral play", "prostate milking", "anal stretching", "cock worship",
  "squirting", "cum play", "creampie", "cum swallowing", "facial cumshot", "cum inflation", "cum control", "teabagging",

  // Gioco di gruppo e dinamiche multiple
  "group stimulation", "gangbang", "threesome", "orgy", "swinging", "public sex", "exhibitionism", "voyeurism", "partner swapping", "partner sharing",
  "soft swap", "hard swap", "multi partner play", "polyamory play", "sensory sharing", "circle jerk", "mutual masturbation",
  "orgy with toys", "group spanking", "group bondage", "gangbang with pegging", "orgy with roleplay",

  // Gioco di dolore e impatto
  "spanking", "whipping", "caning", "flogging", "paddling", "breast torture", "cock and ball torture", "pain play", "impact play",
  "clamping", "needle play", "scarification", "branding", "slash play", "bloodletting", "pressure point play",
  "caning with cane", "boot worship with impact", "sensory pain play", "thumbscrews", "knife edge play", "wax dripping",

  // Gioco medico e di igiene
  "medical play", "enema play", "catheter play", "piercing play", "needle play", "blood play", "breath play", "anal training", "prostate massage",
  "sounding", "temperature probes", "rectal dilators", "dental gag", "cavity search play",
  "medical examination roleplay", "injection play", "enema administration", "anal hygiene ritual",

  // Pratiche di umiliazione e degradazione
  "humiliation", "verbal humiliation", "public humiliation", "degradation", "objectification", "forced feminization", "cuckolding humiliation",
  "shaming", "foot worship humiliation", "diaper humiliation", "pet play humiliation",
  "slut training", "forced chastity humiliation", "name calling", "public degradation", "forced servitude humiliation",

  // Fetish e kink meno comuni o particolari
  "vore", "spectrophilia", "robot fetish", "giantess fetish", "giant/slave play", "tentacle play", "inflation fetish", "diaper fetish", "age regression", "masochism", "sadism",
  "inflation play", "micro/macro play", "vore play", "monster play", "monster girl", "monster boy", "doll fetish", "puppet play",
  "giant robot fetish", "inflation roleplay", "ageplay regression", "robot pet play", "monster tentacle bondage",

  // Altri kink e giochi
  "role reversal", "crossdressing", "gender play", "body modification play", "sensory deprivation", "ear play", "mouth gag", "breath control", "knife play", "edge play", "sploshing", "food play",
  "sensation deprivation", "dark room play", "mask play", "costume play", "latex worship", "fisting glove",
  "consensual non-consent", "chastity device play", "sensation swap", "hypnosis", "mindfuck", "forced orgasm control",
  "clothing destruction", "public nudity", "body painting", "tattoo play", "scat play", "watersports", "humble posture training",

  // Stimolazione mentale e psicologica
  "mind control", "hypnosis play", "brainwashing", "consensual non-consent", "psychological domination", "fantasy play",
  "forced bi", "brainfuck", "memory play", "identity play", "delusion play", "confusion play", "forced perspective",
  "blackmail play", "fear play", "sensory confusion", "obedience conditioning", "role enforcement",

  // Pratiche di cura e attenzione
  "aftercare", "sensual massage", "comfort play", "bonding rituals",
  "cuddle sessions", "protective holding", "slow touch", "verbal reassurance", "emotional support", "trust building",
  "emotional aftercare", "warm blankets", "hydration care", "calming rituals",

  // Altre pratiche comuni
  "tease and denial", "sensory overload", "sensory deprivation", "forced exhibitionism", "clothing destruction", "object insertion", "public play", "private play",
  "breast bondage", "chastity play", "humble posture training", "obedience conditioning", "body worship rituals",
  "forced chastity", "leash training", "obedience punishment", "verbal command", "forced servitude"
];

// 🔁 Funzione per estrarre opzioni uniche
function getUniqueRandoms(pool, count) {
  const clone = [...pool];
  const selected = [];
  for (let i = 0; i < count && clone.length > 0; i++) {
    const idx = Math.floor(Math.random() * clone.length);
    selected.push(clone.splice(idx, 1)[0]);
  }
  return selected;
}

// ▶️ Genera tutto
document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("generateBtn").addEventListener("click", () => {
    console.log("Bottone cliccato!");

    // Inizio tabella Bootstrap con classi base
    let result = `
      <h5>Fantasy Parameters:</h5>
      <table class="table table-dark table-striped table-bordered rounded">
        <thead>
          <tr>
            <th>Categoria</th>
            <th>Valore</th>
          </tr>
        </thead>
        <tbody>
    `;

    // Categorie standard
    for (const [category, options] of Object.entries(categories)) {
      const label = category.charAt(0).toUpperCase() + category.slice(1);
      result += `
        <tr>
          <td><strong>${label}</strong></td>
          <td>${getUniqueRandoms(options, 1)[0]}</td>
        </tr>
      `;
    }

    // Species con probabilità
    result += `
      <tr>
        <td><strong>Character Species</strong></td>
        <td>${getSpeciesByProbability()}</td>
      </tr>
    `;

    // Oggetti coinvolti
    const randomIdx1 = Math.floor(Math.random() * 6) + 2;
    const objects = getUniqueRandoms(objectPool, randomIdx1);
    objects.forEach((obj, idx) => {
      result += `
        <tr>
          <td><strong>Object ${idx + 1}</strong></td>
          <td>${obj}</td>
        </tr>
      `;
    });

    // Kink / atti
    const randomIdx2 = Math.floor(Math.random() * 6) + 2;
    const kinks = getUniqueRandoms(kinkPool, randomIdx2);
    kinks.forEach((kink, idx) => {
      result += `
        <tr>
          <td><strong>Kink ${idx + 1}</strong></td>
          <td>${kink}</td>
        </tr>
      `;
    });

    result += `
        </tbody>
      </table>
    `;

    document.getElementById("fantasyOutput").innerHTML = result;
  });
});


document.addEventListener("DOMContentLoaded", () => {
  displayCategoryOptions();
});
function displayCategoryOptions() {
  const container = document.getElementById("optionsAccordion");
  let accordionHTML = "";
  let index = 0;

  function createAccordionItem(title, items) {
    const id = `collapse${index++}`;
    return `
      <div class="accordion-item">
        <h2 class="accordion-header" id="heading${id}">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#${id}" aria-expanded="false" aria-controls="${id}">
            ${title}
          </button>
        </h2>
        <div id="${id}" class="accordion-collapse collapse" aria-labelledby="heading${id}" data-bs-parent="#optionsAccordion">
          <div class="accordion-body bg-dark text-white">
            <ul class="mb-0">${items.map(item => `<li>${item}</li>`).join("")}</ul>
          </div>
        </div>
      </div>
    `;
  }

  // Categorie standard
  for (const [category, options] of Object.entries(categories)) {
    const label = category.charAt(0).toUpperCase() + category.slice(1);
    accordionHTML += createAccordionItem(label, options);
  }

  // Oggetti
  accordionHTML += createAccordionItem("Object Pool", objectPool);

  // Kink
  accordionHTML += createAccordionItem("Kink Pool", kinkPool);

  // Specie (testuale)
  accordionHTML += createAccordionItem("Character Species (Probability)", [
    "70% humans only",
    "20% humanoid creatures (e.g., demons, succubi)",
    "5% mix of humanoids and beasts",
    "5% beasts only"
  ]);

  container.innerHTML = accordionHTML;
}

document.addEventListener("DOMContentLoaded", () => {
  displayCategoryOptions();
});